INSERT INTO areas (id,name) VALUES
('HQ72D','Development'),
('715I7','Design'),
('FE57Z','Athletic'),
('JFC4V','Personal'),
('ILC5E','Nails'),
('PYQ34','Waxing'),
('HJJLW','Makeup'),
('QGO10','Review'),
('S6E74','Witness'),
('625KG','Sitter'),
('7WN19','Grooming'),
('XHQHO','Walking'),
('LIIIS','Giver'),
('EUF5S','Planning'),
('L4KXU','Performer'),
('GL2FO','College Tutoring'),
('SI8VQ','Elementary School Tutoring'),
('UJSJI','Middle School Tutoring'),
('DAHL9','High School Tutoring'),
('6HDMU','Test Preperation'),
('2BIMB','Residential'),
('UB9I8','Commercial'),
('42IYR','Taxes'),
('OVZFJ','Lessons'),
('ISL35','Small Vehicle Repair'),
('JWVPI','Small Vehicle Maintenance'),
('RX59D','Small Vehicle Upgrades'),
('6VG3X','Classic'),
('I9G34','Modern'),
('RODS5','Amateur'),
('SNDFA','Professional'),
('KZNEO','Production');
commit;
