INSERT INTO categories_specialties (id,name) VALUES

('2E6YQ','Commercial'),
('RYCYR','Personal'),
('PMR9K','Gymnastics'),
('FMFV1','Tennis'),
('HYIXR','Soccer'),
('A167D','Mixed Martial Arts'),
('3KXQQ','Martial Arts'),
('M0KN4','Flexibility'),
('YQVWO','Conditioning'),
('MU793','Strength'),
('4QZVM','Manicure'),
('KMV9A','Acrylic Tips'),
('Y079O','Nail Art'),
('JC7MU','Cuticle Removal'),
('P19WX','Paraffin Treatment'),
('8YAB5','Pedicure'),
('DCWV6','Eyebrows'),
('9OHU7','Arms'),
('NRFT4','Legs'),
('56CH4','Bikini Line'),
('5PYOU','Full Brazilian'),
('P5IN7','Glamarous'),
('9XEL5','Special FX'),
('KY40T','Documents'),
('KQT5J','Notary'),
('WEVER','Dogs'),
('FVM0H','Birds'),
('11J1J','Cats'),
('FN91D','0 - 1 Years of Age'),
('7LM93','2 - 5 Years of Age'),
('10KZ6','6 - 10 Years of Age'),
('JB7BZ','11 - 12 Years of Age'),
('7FXLW','18 - 21 Years of Age'),
('P805A','22 - 25 Years of Age'),
('MXS2X','26 - 30 Years of Age'),
('V89DZ','31 - 40 Years of Age'),
('AZX8N','40 - 50 Years of Age'),
('OBW2Q','50 - 60 Years of Age'),
('NC649','70 - 80 Years of Age'),
('4DWC6','Formal'),
('WHUCQ','Casual'),
('HIVT0','DJ'),
('6RGCT','Magician'),
('1H0LX','Clown'),
('EM53V','English I'),
('2HRC4','English II'),
('75OUR','Calculus I'),
('33Y93','Calculus II'),
('MLLHE','Trigonometry'),
('Q6BC2','Differential Equations'),
('94XX2','Chemistry I'),
('7LCC2','Chemistry II'),
('4C3SZ','Physics I'),
('OJY5C','Physics II'),
('NJQ5U','Biology I'),
('KNHHX','Biology II'),
('JSOTF','Discrete Mathematics'),
('LJORZ','French I'),
('OHUX0','French II'),
('GIVW9','Spanish I'),
('Q08H3','Spanish II'),
('JPUI4','Organic Chemistry'),
('MYLIB','Math'),
('RPAIF','Science'),
('T0VHK','Reading'),
('68T5L','Geometry'),
('L2YIE','English'),
('T5T84','Algebra'),
('Q4M9C','Algebra I'),
('128YS','Algebra II'),
('O30HN','SAT Prep'),
('YXH1S','GRE Prep'),
('S0AJU','GED Prep'),
('CSQPP','ACT Prep'),
('7LOPT','Bathrooms'),
('VEBKI','Bedrooms'),
('UNIPL','Dining Rooms'),
('A5UXC','Laundry'),
('KMHC5','Kitchen'),
('H4INJ','Small Offices'),
('E73GY','Large Offices'),
('VIH0O','Personal Preparation'),
('EJ40P','Commercial Preparation'),
('WAUMJ','Piano'),
('Y5Y61','Guitar'),
('Y60EL','Violin'),
('0B8SW','Cello'),
('7426E','Flute'),
('SRRZW','Bass Guitar'),
('A11CL','Drums'),
('5K6VU','Singing'),
('BU170','Alternator'),
('AAMMY','Oxygen Sensor'),
('8GKK4','Master Brake Cylinder'),
('814CI','Catalytic Converter'),
('VNZ7U','Oil Change'),
('2ETSS','Spark Plugs'),
('YM55G','Thermostat'),
('ZEHAO','Tire Rotation'),
('GOGIR','Battery'),
('N9OH0','AC Filter'),
('BTQUJ','Brakes'),
('7II1U','Alarms'),
('0K38A','Subwoofers'),
('BIAK8','HID Lights'),
('R8RYI','Tints'),
('9ZRG2','Waltz'),
('OZ6OC','Ballroom'),
('A8IME','Ballet'),
('D5T7F','Interpretative'),
('2P1VO','Merengue'),
('FE4O3','Rumba'),
('A9J3W','Tango'),
('XYD2M','Cha-Cha'),
('ZX7DI','Foxtrot'),
('8JVAD','Salsa'),
('FNX9Y','Hip-Hop'),
('XOJMP','Camera'),
('T3GDJ','Video'),
('H3H0J','Interior'),
('XMVKC','Fashion'),
('BWOI2','Marketing'),
('4YWCN','Graphic'),
('Y3BGR','Sculpting'),
('4Z3SL','Painting'),
('GNNXL','Drawing'),
('F39TB','Audio'),
('LHPG0','Animation'),
('A8K9Z','Film');
commit;